#:schema https://starship.rs/config-schema.json

add_newline = true

[character]
success_symbol = "ğŸ¦„"
error_symbol = "ğŸš¨"
vimcmd_replace_one_symbol = "ğŸ´"
vimcmd_replace_symbol = "ğŸ´"
vimcmd_symbol = "ğŸ¦„"
vimcmd_visual_symbol = "ğŸ´"
