#:schema https://starship.rs/config-schema.json

add_newline = true

[direnv]
symbol = "ğŸŒ "
style = "bold green"
format = 'is [${symbol}${allowed}${loaded}]($style) '
disabled = true
allowed_msg = ""
denied_msg = "**"
not_allowed_msg = "*"
unloaded_msg = "unloaded"
detect_files = [".envrc", ".env"]

[typst]
symbol = "ğŸ“ "

[directory]
truncation_length = 4

[gcloud]
disabled = true
