#:schema https://starship.rs/config-schema.json

add_newline = true

[character]
success_symbol = "ğŸ¦„ [â¯](green)"
error_symbol = "ğŸ¦„ [â¯](red)"
vimcmd_symbol = "ğŸ¦„ [â®](subtext1)"
vimcmd_replace_one_symbol = "ğŸ¦„ [â®](purple)"
vimcmd_replace_symbol = "ğŸ¦„ [â®](purple)"
vimcmd_visual_symbol = "ğŸ¦„ [â®](yellow)"

[direnv]
symbol = "ğŸŒ "
style = "bold green"
format = 'is [${symbol}${allowed}${loaded}]($style) '
disabled = false
allowed_msg = ""
denied_msg = "**"
not_allowed_msg = "*"
unloaded_msg = "unloaded"
detect_files = [".envrc", ".env"]

[directory]
truncation_length = 4
